[
    {
        id: 'K_HV001',
        title: 'HV-001',
        addClassName: { subText: '', mainText: 'valve' },
        panelId: 54,
        position: 'left center',
    },
    {
        id: 'K_HV004',
        title: 'HV-004',
        addClassName: { subText: 'hv-004', mainText: 'valve' },
        panelId: 56,
        position: 'left center',
    },
    {
        id: 'K_HV007',
        title: 'HV-007',
        addClassName: { subText: 'hv-007', mainText: 'valve' },
        panelId: 58,
        position: 'left center',
    },
    {
        id: 'K_TE005',
        title: 'TE-005',
        addClassName: { subText: 'temp te-005', mainText: 'temp' },
        panelId: 42,
        position: 'top center',
    },
    {
        id: 'K_TE006',
        title: 'TE-006',
        addClassName: { subText: 'temp te-006', mainText: 'temp' },
        panelId: 50,
        position: 'left center',
    },
    {
        id: 'K_TE007',
        title: 'TE-007',
        addClassName: { subText: 'temp te-007', mainText: 'temp' },
        panelId: 52,
        position: 'left center',
    },
    {
        id: 'K_TE008',
        title: 'TE-008',
        addClassName: { subText: 'temp te-008', mainText: 'temp' },
        panelId: 60,
        position: 'left center',
    },
    {
        id: 'VV1_TE009',
        title: 'TE-009',
        addClassName: { subText: 'temp te-009', mainText: 'temp' },
        panelId: 30,
        position: 'left bottom',
    },
    {
        id: 'VV1_TE010',
        title: 'TE-010',
        addClassName: { subText: 'temp te-010', mainText: 'temp' },
        panelId: 32,
        position: 'left top',
    },
    {
        id: 'VV2_TE011',
        title: 'TE-011',
        addClassName: { subText: 'temp te-011', mainText: 'temp' },
        panelId: 34,
        position: 'left bottom',
    },
    {
        id: 'VV2_TE012',
        title: 'TE-012',
        addClassName: { subText: 'temp te-012', mainText: 'temp' },
        panelId: 36,
        position: 'left top',
    },
    {
        id: 'VV3_TE013',
        title: 'TE-013',
        addClassName: { subText: 'temp te-013', mainText: 'temp' },
        panelId: 38,
        position: 'left bottom',
    },
    {
        id: 'VV3_TE014',
        title: 'TE-014',
        addClassName: { subText: 'temp te-014', mainText: 'temp' },
        panelId: 40,
        position: 'left top',
    },
    {
        id: 'K_TE018',
        title: 'TE-018',
        addClassName: { subText: 'temp te-018', mainText: 'temp' },
        panelId: 46,
        position: 'top center',
    },
    {
        id: 'K_TE019',
        title: 'TE-019',
        addClassName: { subText: 'temp te-019', mainText: 'temp' },
        panelId: 48,
        position: 'top center',
    },
    {
        id: 'K_TE001',
        title: 'TE-001',
        addClassName: { subText: 'temp te-001', mainText: 'temp' },
        panelId: 44,
        position: 'top center',
    },
    {
        id: 'AK_TE001',
        title: 'TE-AK-001',
        addClassName: { subText: 'temp te-roof-001', mainText: 'temp' },
        panelId: 8,
        position: 'right center',
    },
    {
        id: 'AK_TE002',
        title: 'TE-002',
        addClassName: { subText: 'temp te-002', mainText: 'temp' },
        panelId: 10,
        position: 'right top',
    },
    {
        id: 'AK_TE003',
        title: 'TE-003',
        addClassName: { subText: 'temp te-003', mainText: 'temp' },
        panelId: 4,
        position: 'bottom center',
    },
    {
        id: 'AKP01_TE004',
        title: 'TE-004',
        addClassName: { subText: 'temp te-004', mainText: 'temp' },
        panelId: 6,
        position: 'right top',
    },
    {
        id: 'AK_FE002',
        title: 'FE-002',
        addClassName: { subText: 'temp fe-002', mainText: 'temp' },
        panelId: 2,
        position: 'right bottom',
    },
    {
        id: 'AKP01_TE004',
        title: 'AK_P_TE',
        addClassName: { subText: 'temp ak-p-qq te', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 16,
        position: 'right center',
      },
      {
        id: 'AK_QQ_D',
        title: 'AK_P_QQ',
        addClassName: { subText: 'temp ak-p-qq', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 12,
        position: 'right center',
      },
      {
        id: 'AKP01_PWM_A',
        title: 'AK_P_PWM',
        addClassName: { subText: 'temp ak-p-qq pwm', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 14,
        position: 'right center',
      },
    {
        id: 'fSpeed',
        title: 'P1_RPM',
        addClassName: { subText: 'temp ak-p-qq p1-2 p1-rpm', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 22,
        position: 'right center',
      },
      {
        id: 'fVolumeFlow',
        title: 'P1_FE',
        addClassName: { subText: 'temp ak-p-qq p1-2 p1-fe', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 20,
        position: 'right center',
      },
      {
        id: 'fHead',
        title: 'P1_PE',
        addClassName: { subText: 'temp ak-p-qq p1-2 p1-pe', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 18,
        position: 'right center',
      },
      {
        id: 'fPumpLiquidTemp',
        title: 'P1_TE',
        addClassName: { subText: 'temp ak-p-qq p1-2', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 62,
        position: 'right center',
      },
    {
        id: 'fSpeed',
        title: 'P2_RPM',
        addClassName: { subText: 'temp ak-p-qq p1-2 p1-rpm p2', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 24,
        position: 'right center',
      },
      {
        id: 'fVolumeFlow',
        title: 'P2_FE',
        addClassName: { subText: 'temp ak-p-qq p1-2 p1-fe p2', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 26,
        position: 'right center',
      },
      {
        id: 'fHead',
        title: 'P2_PE',
        addClassName: { subText: 'temp ak-p-qq p1-2 p1-pe p2', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 28,
        position: 'right center',
      },
      {
        id: 'fPumpLiquidTemp',
        title: 'P2_TE',
        addClassName: { subText: 'temp ak-p-qq p1-2 p2', subTextDiv: 'p1-p2-sub', mainText: 'temp' },
        panelId: 64,
        position: 'right center',
      }
]